# Generated by Django 2.2.2 on 2019-07-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun7app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Email_blnk',
            field=models.EmailField(max_length=254),
        ),
    ]
